/**
 * Outline Step Handler — quinto step do pipeline editorial
 *
 * Consome: book_dna, theme_decision.
 * Produz: outline — lista estruturada de capítulos com título, sinopse,
 *         key points e estimativa de tamanho.
 *
 * Outcome: `completed`. O outline é crítico mas não pede gate por default —
 *          a revisão humana acontece na editorial_qa quando os drafts já
 *          existem. Se o produto quiser um gate intermediário no outline,
 *          basta trocar o outcome para 'awaiting_approval' sem mudar schema.
 *
 * Forma do artefato documentada em `OutlineContent` — consumida diretamente
 * por `chapter-writing` via `priorArtifacts`.
 */

import type {
  IBookStepHandler,
  BookStepResult,
} from '../../../domain/interfaces/book-step-handler.js';
import type { BookEditorialContext } from '../../../domain/entities/book-editorial-context.js';
import type { BookArtifact } from '../../../domain/entities/book-editorial.js';
import { logger } from '../../../utils/logger.js';

/**
 * Forma estruturada do artefato `outline`. `chapter_writing` espera
 * exatamente este shape via `JSON.parse(artifact.content)`.
 */
export interface OutlineChapter {
  number: number;
  title: string;
  synopsis: string;
  keyPoints: string[];
  estimatedWords: number;
}

export interface OutlineContent {
  sourceDnaArtifactId: string;
  sourceThemeArtifactId: string;
  chapters: OutlineChapter[];
  totalChapters: number;
  estimatedTotalWords: number;
  placeholder: boolean;
  generatedAt: string;
}

function findArtifact(
  priors: readonly BookArtifact[],
  kind: BookArtifact['kind'],
): BookArtifact | null {
  return priors.find((a) => a.kind === kind) ?? null;
}

/** Constrói um outline placeholder com 6 capítulos genéricos. */
function buildPlaceholderChapters(): OutlineChapter[] {
  const count = 6;
  const chapters: OutlineChapter[] = [];
  for (let i = 1; i <= count; i++) {
    chapters.push({
      number: i,
      title: `Chapter ${i}`,
      synopsis: `Placeholder synopsis for chapter ${i} — to be generated by LLM.`,
      keyPoints: [],
      estimatedWords: 2500,
    });
  }
  return chapters;
}

export class OutlineStepHandler implements IBookStepHandler {
  readonly step = 'outline' as const;
  readonly name = 'Outline';

  async run(ctx: BookEditorialContext): Promise<BookStepResult> {
    const dna = findArtifact(ctx.priorArtifacts, 'book_dna');
    const theme = findArtifact(ctx.priorArtifacts, 'theme_decision');

    if (!dna) {
      return {
        outcome: 'failed',
        artifacts: [],
        error: 'Outline: book_dna artifact not found — run book_dna step first',
      };
    }
    if (!theme) {
      return {
        outcome: 'failed',
        artifacts: [],
        error: 'Outline: theme_decision artifact not found',
      };
    }

    const chapters = buildPlaceholderChapters();
    const estimatedTotal = chapters.reduce((acc, c) => acc + c.estimatedWords, 0);

    const content: OutlineContent = {
      sourceDnaArtifactId: dna.id,
      sourceThemeArtifactId: theme.id,
      chapters,
      totalChapters: chapters.length,
      estimatedTotalWords: estimatedTotal,
      placeholder: true,
      generatedAt: new Date().toISOString(),
    };

    logger.info(
      `[OutlineStepHandler] Built outline for job ${ctx.job.id} ` +
      `(${chapters.length} chapters, ~${estimatedTotal} words)`,
    );

    return {
      outcome: 'completed',
      artifacts: [
        {
          kind: 'outline',
          title: `Outline: ${ctx.job.title}`,
          content: content as unknown as Record<string, unknown>,
        },
      ],
      metrics: {
        totalChapters: chapters.length,
        estimatedTotalWords: estimatedTotal,
      },
    };
  }
}
